### ISSUE TITLE
fluentd fails for missing unix domain socket

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#561]
this is one of those toss-ups on whether or not we want to support this - i haven't delved into the code yet but if it's a case where it spawns a bunch of processes and then uses this to communicate between them that's obviously not a usecase but I don't actually know if that's the case or not

as you can see there is a mention of a 'supervisor' and ruby doesn't have real threads so this might actually be that case - needs some further investigation

```
2019-02-27 19:33:21 +0000 [info]: fluent/log.rb:322:info: starting fluentd-1.4.0 pid=1 ruby="2.3.1"
2019-02-27 19:33:21 +0000 [info]: fluent/log.rb:322:info: spawn command to main:  cmdline=["/usr/bin/ruby2.3", "-Eascii-8bit:ascii-8bit", "/.gem/ruby/2.3.0/bin/fluentd", "-c", "/fluent/fluent.conf", "-vv", "--under-supervisor"]
Unexpected error Address family not supported by protocol - socket(2) for /tmp/SERVERENGINE_SOCKETMANAGER_2019-02-27T19:33:21Z_1
  /.gem/ruby/2.3.0/gems/serverengine-2.1.0/lib/serverengine/socket_manager_unix.rb:75:in `initialize'
  /.gem/ruby/2.3.0/gems/serverengine-2.1.0/lib/serverengine/socket_manager_unix.rb:75:in `new'
  /.gem/ruby/2.3.0/gems/serverengine-2.1.0/lib/serverengine/socket_manager_unix.rb:75:in `start_server'
  /.gem/ruby/2.3.0/gems/serverengine-2.1.0/lib/serverengine/socket_manager.rb:94:in `initialize'
  /.gem/ruby/2.3.0/gems/serverengine-2.1.0/lib/serverengine/socket_manager.rb:87:in `new'
  /.gem/ruby/2.3.0/gems/serverengine-2.1.0/lib/serverengine/socket_manager.rb:87:in `open'
  /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/supervisor.rb:65:in `before_run'
  /.gem/ruby/2.3.0/gems/serverengine-2.1.0/lib/serverengine/server.rb:125:in `main'
  /.gem/ruby/2.3.0/gems/serverengine-2.1.0/lib/serverengine/daemon.rb:119:in `main'
  /.gem/ruby/2.3.0/gems/serverengine-2.1.0/lib/serverengine/daemon.rb:68:in `run'
  /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/supervisor.rb:632:in `supervise'
  /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/supervisor.rb:502:in `run_supervisor'
  /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
  /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /.gem/ruby/2.3.0/gems/fluentd-1.4.0/bin/fluentd:8:in `<top (required)>'
  /.gem/ruby/2.3.0/bin/fluentd:23:in `load'
  /.gem/ruby/2.3.0/bin/fluentd:23:in `<main>'
exit_group
exit status 1
```

```
eyberg@dungeon:~/fl$ cat config.json
{
  "Args": ["/.gem/ruby/2.3.0/bin/fluentd", "-c", "/fluent/fluent.conf", "-vv"],
  "Dirs": ["fluent"],
  "Files": ["/lib/x86_64-linux-gnu/librt.so.1", "/lib/x86_64-linux-gnu/libz.so.1", "/lib/x86_64-linux-gnu/libssl.so.1.0.0", "/lib/x86_64-linux-gnu/libcrypto.so.1.0.0"],
  "MapDirs": {"/home/eyberg/.gem/*": "/.gem" }
}
```

install instructions taken from 

https://docs.fluentd.org/v1.0/articles/install-by-gem

for implementation/test case:

https://github.com/troydhanson/network/blob/master/unixdomain/01.basic/cli.c
https://github.com/troydhanson/network/blob/master/unixdomain/01.basic/srv.c
http://man7.org/linux/man-pages/man7/unix.7.html

**Comment by eyberg** [comment]
w/ up to https://github.com/nanovms/nanos/pull/1100 ->

```
2020-03-31 21:56:24 +0000 [error]: fluent/log.rb:362:error: unexpected error error_class=Errno::ENOTCONN error="Transport endpoint is not connected - recvmsg(2)"
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/serverengine-2.1.0/lib/serverengine/socket_manager_unix.rb:37:in `recv_io'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/serverengine-2.1.0/lib/serverengine/socket_manager_unix.rb:37:in `recv'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/serverengine-2.1.0/lib/serverengine/socket_manager.rb:56:in `listen'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/serverengine-2.1.0/lib/serverengine/socket_manager.rb:64:in `listen_tcp'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/plugin/in_http.rb:138:in `start'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/root_agent.rb:203:in `block in start'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/root_agent.rb:192:in `block (2 levels) in lifecycle'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/root_agent.rb:191:in `each'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/root_agent.rb:191:in `block in lifecycle'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/root_agent.rb:178:in `each'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/root_agent.rb:178:in `lifecycle'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/root_agent.rb:202:in `start'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/engine.rb:274:in `start'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/engine.rb:219:in `run'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/supervisor.rb:801:in `run_engine'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/supervisor.rb:549:in `block in run_worker'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/supervisor.rb:726:in `main_process'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/supervisor.rb:544:in `run_worker'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/gems/fluentd-1.4.0/bin/fluentd:8:in `<top (required)>'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/bin/fluentd:23:in `load'
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:549:block in run_worker: /.gem/ruby/2.3.0/bin/fluentd:23:in `<main>'
2020-03-31 21:56:24 +0000 [error]: fluent/log.rb:362:error: unexpected error error_class=Errno::ENOTCONN error="Transport endpoint is not connected - recvmsg(2)"
  2020-03-31 21:56:24 +0000 [error]: fluent/supervisor.rb:725:main_process: suppressed same stacktrace
```

**Comment by francescolavra** [comment]
With #1248, it gets past the recvmsg() error, but then fails with `/usr/local/lib/ruby/gems/2.7.0/gems/serverengine-2.2.1/lib/serverengine/socket_manager_unix.rb:37: [BUG] rsock_detect_cloexec: fcntl(-1, F_GETFD) failed: Bad file descriptor`. The reason for this failure is that fluentd uses the send_io() and recv_io() methods of the UNIXSocket class (https://www.rubydoc.info/stdlib/socket/2.2.2/UNIXSocket), which internally use sendmsg() and recvmsg() to transfer ancillary data, which we don't support; more specifically, those methods transfer data of type SCM_RIGHTS, which is used to send or receive a set of open file descriptors (see `man 7 unix`). The usage of SCM_RIGHTS ancillary data is mostly relevant in inter-process communication, but fluentd uses it even within a single process.

**Comment by francescolavra** [comment]
https://github.com/nanovms/nanos/issues/1692

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/issues/1339
