### ISSUE TITLE
django / python 2.7 fails w/ 'allocate table failed'

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#569]
seems like mkfs is puking on it for some reason - either cause of the size of the image or more than likely the number of files (i've triggered this sort of behavior before w/a lot of files)

it loaded all of this shit ->
```
eyberg@s1:~/dj$ find /home/eyberg/.local/ -type f | wc -l
5027
```

```
eyberg@s1:~/dj$ ops load python_2.7.15rc1 -c config.json -p 8000
Extracting /home/eyberg/.ops/packages/python_2.7.15rc1.tar.gz to /home/eyberg/.ops/.staging/python_2.7.15rc1
[python mysite/manage.py runserver]
2019/02/27 23:41:24 allocate table failed

panic: exit status 2

goroutine 1 [running]:
main.loadCommandHandler(0xc420259b80, 0xc4204ca1e0, 0x1, 0x5)
        /home/eyberg/go/src/github.com/nanovms/ops/ops.go:408 +0x1d30
github.com/spf13/cobra.(*Command).execute(0xc420259b80, 0xc4204ca190, 0x5, 0x5, 0xc420259b80, 0xc4204ca190)
        /home/eyberg/go/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc4201f4280, 0x0, 0xc420259b80, 0xc4201f43d0)
        /home/eyberg/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0xc4201f4280, 0xc420091eb8, 0x1)
        /home/eyberg/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /home/eyberg/go/src/github.com/nanovms/ops/ops.go:630 +0x1503
```

```
eyberg@s1:~/dj$ tree
.
├── config.json
├── mysite
│   ├── db.sqlite3
│   ├── manage.py
│   └── mysite
│       ├── __init__.py
│       ├── __init__.pyc
│       ├── settings.py
│       ├── settings.pyc
│       ├── urls.py
│       ├── urls.pyc
│       ├── wsgi.py
│       └── wsgi.pyc
└── tempimage

2 directories, 12 files
eyberg@s1:~/dj$ cat config.json
{
  "MapDirs": {"/home/eyberg/.local/*": "/.local" },
  "Args": ["mysite/manage.py", "runserver"],
  "Dirs": ["mysite"]
}
```

this is where pip will install the python packages locally to give you an idea on size cause that's prob. what I think this is bitching about

```
eyberg@s1:~/dj$ du -sh ~/.local/
48M     /home/eyberg/.local/
```

**Comment by francescolavra** [comment]
The `allocate table failed` error was fixed in #947. More recently, a regression has been introduced which was causing a different error; this error is fixed by #1377, and I'm now able to create an image starting from the python 2.7 package and adding in the manifest 12000+ files (500+ MB).
