### ISSUE TITLE
ipfs tracking tkt

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#643]
```
eyberg@dungeon:~/go-ipfs$ ops run -p 4001 -c config.json ipfs
Finding dependent shared libs
booting /home/eyberg/.ops/images/ipfs.img ...
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
assigned: 10.0.2.15
panic: runtime error: index out of range

goroutine 1 [running]:
gx/ipfs/QmcaSwFc5RBg8yCq54QURwEU4nwjfCpjbpmaAm4VbdGLKv/go-logging.init()
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmcaSwFc5RBg8yCq54QURwEU4nwjfCpjbpmaAm4VbdGLKv/go-logging/format.go:87 +0x224
exit status 5
eyberg@dungeon:~/go-ipfs$ cat config.json
{
 "Env": {
        "IPFS_PATH": ".ipfs"
    },
  "Dirs": [".ipfs"]
}
```

seems like something might be overwriting something else

**Comment by eyberg** [comment]
https://github.com/nanovms/nanos/pull/1027

**Comment by eyberg** [comment]
wants netlink - not sure if this is absolutely necessary though

```
16:30:57.178 ERROR    p2pnode: mdns error:  could not determine host IP addresses for nanovms. discovery.go:46
16:30:57.189 ERROR   cmd/ipfs: error from node construction:  route ip+net: netlinkrib: address family not supported by protocol daemon.go:337

Error: route ip+net: netlinkrib: address family not supported by protocol
```

**Comment by francescolavra** [comment]
Netlink is now supported, but for mDNS to work we need multicast support as well. Anyway, mDNS can be disabled in the ipfs configuration.
I made a package (with mDNS disabled): https://repo.ops.city/v2/packages/francescolavra/ipfs/show
