### ISSUE TITLE
crashing self-signed tls cert on gce

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#766]
```
SeaBIOS (version 1.8.2-20190322_093631-google)
Total RAM Size = 0x0000000080000000 = 2048 MiB
CPUs found: 1     Max CPUs supported: 1
found virtio-scsi at 0:3
virtio-scsi vendor='Google' product='PersistentDisk' rev='1' type=0 removable=0
virtio-scsi blksize=512 sectors=2097152 = 1024 MiB
drive 0x000f2a20: PCHS=0/0/0 translation=lba LCHS=1024/32/63 s=2097152
Booting from Hard Disk 0...
assigned: 10.240.0.34
2019/04/23 23:12:24 http: TLS handshake error from 173.13.162.162:52878: remote error: tls: unknown certificate
2019/04/23 23:12:24 http: TLS handshake error from 173.13.162.162:52879: remote error: tls: unknown certificate
2019/04/23 23:12:25 http: TLS handshake error from 173.13.162.162:52881: remote error: tls: unknown certificate
2019/04/23 23:12:25 http: TLS handshake error from 173.13.162.162:52882: remote error: tls: unknown certificate
2019/04/23 23:12:28 http: TLS handshake error from 173.13.162.162:52884: remote error: tls: unknown certificate
2019/04/23 23:12:28 http: TLS handshake error from 173.13.162.162:52883: remote error: tls: unknown certificate
2019/04/23 23:13:01 http2: received GOAWAY [FrameHeader GOAWAY len=20], starting graceful shutdown
2019/04/23 23:13:01 http: TLS handshake error from 173.13.162.162:52894: remote error: tls: unknown certificate
2019/04/23 23:13:01 http2: server: error reading preface from client 173.13.162.162:52895: local error: tls: bad record MAC
2019/04/23 23:13:07 http: TLS handshake error from 173.13.162.162:52898: remote error: tls: unknown certificate
2019/04/23 23:13:07 http2: server: error reading preface from client 173.13.162.162:52899: local error: tls: bad record MAC
2019/04/23 23:13:10 http: TLS handshake error from 173.13.162.162:52901: remote error: tls: unknown certificate
2019/04/23 23:13:10 http2: server: error reading preface from client 173.13.162.162:52902: local error: tls: bad record MAC
2019/04/23 23:13:18 http: TLS handshake error from 173.13.162.162:52903: remote error: tls: unknown certificate
2019/04/23 23:13:19 http2: server: error reading preface from client 173.13.162.162:52904: local error: tls: bad record MAC
2019/04/23 23:13:21 http: TLS handshake error from 173.13.162.162:52905: remote error: tls: unknown certificate
2019/04/23 23:13:21 http2: server: error reading preface from client 173.13.162.162:52906: local error: tls: bad record MAC
2019/04/23 23:13:28 http: TLS handshake error from 173.13.162.162:52907: remote error: tls: unknown certificate
2019/04/23 23:13:28 http2: server: error reading preface from client 173.13.162.162:52908: local error: tls: bad record MAC
2019/04/23 23:14:01 http: TLS handshake error from 173.13.162.162:52950: remote error: tls: unknown certificate
2019/04/23 23:14:01 http2: server: error reading preface from client 173.13.162.162:52951: local error: tls: bad record MAC
2019/04/23 23:14:50 http: TLS handshake error from 173.13.162.162:52966: EOF
fatal error: index out of range

runtime stack:
runtime.throw(0x6e89db, 0x12)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.panicindex()
	/usr/local/go/src/runtime/panic.go:41 +0x8e
runtime.netpoll(0xc000014001, 0x1)
	/usr/local/go/src/runtime/netpoll_epoll.go:81 +0x18b
runtime.findrunnable(0xc000014000, 0x0)
	/usr/local/go/src/runtime/proc.go:2380 +0x505
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2525 +0x20e
runtime.park_m(0xc0000e8000)
	/usr/local/go/src/runtime/proc.go:2605 +0xa1
runtime.mcall(0x7395d0)
	/usr/local/go/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7000084f08, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0000b2018, 0x72, 0x0, 0x0, 0x6e5b5c)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000b2000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc0000b2000, 0x1, 0x1000000000000, 0x2f8)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00000e038, 0xc000000180, 0x3, 0xc000014070)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).AcceptTCP(0xc00000e038, 0x42a7c1, 0x6fa718, 0xc00044dc68)
	/usr/local/go/src/net/tcpsock.go:247 +0x48
net/http.tcpKeepAliveListener.Accept(0xc00000e038, 0xc03a7be0c8, 0x3a7be0c80044dc90, 0x5cbf9c79, 0xc00044dc90)
	/usr/local/go/src/net/http/server.go:3264 +0x2f
crypto/tls.(*listener).Accept(0xc000264dc0, 0xc00044dce0, 0x18, 0xc000000180, 0x6248a4)
	/usr/local/go/src/crypto/tls/tls.go:62 +0x37
net/http.(*Server).Serve(0xc000054a90, 0x747140, 0xc000264dc0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2859 +0x22d
net/http.(*Server).ServeTLS(0xc000054a90, 0x747600, 0xc00000e038, 0x6e6848, 0xa, 0x6e6852, 0xa, 0x747240, 0xc00000e038)
	/usr/local/go/src/net/http/server.go:2924 +0x26b
net/http.(*Server).ListenAndServeTLS(0xc000054a90, 0x6e6848, 0xa, 0x6e6852, 0xa, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:3081 +0x169
net/http.ListenAndServeTLS(...)
	/usr/local/go/src/net/http/server.go:3047
main.main()
	/Users/eyberg/go/src/github.com/nanovms/pkghub/main.go:43 +0x141

goroutine 79 [select]:
net/http.(*http2serverConn).serve(0xc0000e8300)
	/usr/local/go/src/net/http/h2_bundle.go:4387 +0x500
net/http.(*http2Server).ServeConn(0xc00003c380, 0x749560, 0xc00002b180, 0xc00044fcf8)
	/usr/local/go/src/net/http/h2_bundle.go:3996 +0x711
net/http.http2ConfigureServer.func1(0xc000054a90, 0xc00002b180, 0x743000, 0xc0000e3d20)
	/usr/local/go/src/net/http/h2_bundle.go:3834 +0x89
net/http.(*conn).serve(0xc00005c820, 0x747b00, 0xc00004d260)
	/usr/local/go/src/net/http/server.go:1802 +0x105a
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4

goroutine 82 [syscall]:
syscall.Syscall(0x0, 0x5, 0xc00016a900, 0x205, 0x49fb81, 0x7000084d68, 0x72)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x5, 0xc00016a900, 0x205, 0x205, 0x0, 0x57c671, 0xc00009c000)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:732 +0x5a
syscall.Read(...)
	/usr/local/go/src/syscall/syscall_unix.go:172
internal/poll.(*FD).Read(0xc0000b2580, 0xc00016a900, 0x205, 0x205, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:165 +0x131
net.(*netFD).Read(0xc0000b2580, 0xc00016a900, 0x205, 0x205, 0x203000, 0x0, 0x118)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e030, 0xc00016a900, 0x205, 0x205, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc00000c380, 0xc00016a900, 0x205, 0x205, 0x63cd61, 0x6e7b1e, 0xc000244ab0)
	/usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc00002b3d8, 0x7422a0, 0xc00000c380, 0x4094d5, 0x6981a0, 0x6d4120)
	/usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc00002b180, 0x742420, 0xc00000e030, 0x5, 0xc00000e030, 0x9)
	/usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc00002b180, 0x6fa700, 0xc00002b2b8, 0xc00027c058)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc00002b180, 0xc00009a118, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1236 +0x137
io.ReadAtLeast(0x70000a18a8, 0xc00002b180, 0xc00009a118, 0x9, 0x9, 0x9, 0x10000005efbe9, 0x0, 0x1)
	/usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
net/http.http2readFrameHeader(0xc00009a118, 0x9, 0x9, 0x70000a18a8, 0xc00002b180, 0x0, 0xc000000000, 0xc000244f28, 0xc00027c120)
	/usr/local/go/src/net/http/h2_bundle.go:1476 +0x88
net/http.(*http2Framer).ReadFrame(0xc00009a0e0, 0xc000244ee0, 0x2, 0x0, 0x1)
	/usr/local/go/src/net/http/h2_bundle.go:1734 +0xa1
net/http.(*http2serverConn).readFrames(0xc0000e8300)
	/usr/local/go/src/net/http/h2_bundle.go:4274 +0xa4
created by net/http.(*http2serverConn).serve
	/usr/local/go/src/net/http/h2_bundle.go:4379 +0x2da

goroutine 89 [IO wait]:
internal/poll.runtime_pollWait(0x7000084e38, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0000b2818, 0x72, 0x200, 0x205, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000b2800, 0xc00016a000, 0x205, 0x205, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0000b2800, 0xc00016a000, 0x205, 0x205, 0x203000, 0x0, 0xc000014058)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e068, 0xc00016a000, 0x205, 0x205, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc00000c400, 0xc00016a000, 0x205, 0x205, 0xc00016a000, 0x0, 0xc000245738)
	/usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc00002acd8, 0x7422a0, 0xc00000c400, 0x4094d5, 0x6981a0, 0x6d4120)
	/usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc00002aa80, 0x742420, 0xc00000e068, 0x5, 0xc00000e068, 0x206cca215b3ad165)
	/usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc00002aa80, 0x405300, 0xc000001200, 0x3)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).readHandshake(0xc00002aa80, 0xc000245a50, 0xc000245a50, 0x43ac7d, 0xc0000407d8)
	/usr/local/go/src/crypto/tls/conn.go:974 +0x6f
crypto/tls.(*Conn).readClientHello(0xc00002aa80, 0xc000245b30, 0x0, 0xc0000624a0)
	/usr/local/go/src/crypto/tls/handshake_server.go:134 +0x40
crypto/tls.(*Conn).serverHandshake(0xc00002aa80, 0x6fa718, 0xc00002abb8)
	/usr/local/go/src/crypto/tls/handshake_server.go:42 +0x84
crypto/tls.(*Conn).Handshake(0xc00002aa80, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1345 +0x1f2
net/http.(*conn).serve(0xc00005cb40, 0x747b00, 0xc00004d4d0)
	/usr/local/go/src/net/http/server.go:1785 +0x187
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```

**Comment by eyberg** [comment]
this is old / not reproducible and all these EOFs don't exist anymore, closing
