### ISSUE TITLE
influxdb 2.0 (beta) tracking tkt - low priority

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#866]
looks like this wants flock which we are tracking here https://github.com/nanovms/nanos/issues/829

```
eyberg@dungeon:~$ grep syscall /tmp/out
debugsyscalls:t
1 nosyscall getgid
            4 nosyscall flock
            4 nosyscall flock
```

**Comment by eyberg** [comment]
some sort of mem corruption? going on here - it's very reproducible though

note: we already support influx 1.7.0

```
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
assigned: 10.0.2.15
ts=2019-11-26T16:35:11.995205Z lvl=info msg="Welcome to InfluxDB" log_id=0JM8uyzG000 version=2.0.0-alpha.13 commit=d30fd1084 build_date=2019-06-14T00:32:50Z
ts=2019-11-26T16:35:12.230162Z lvl=info msg="Resources opened" log_id=0JM8uyzG000 service=bolt path=/root/.influxdbv2/influxd.bolt
panic: page 3 already freed

goroutine 1 [running]:
github.com/coreos/bbolt.(*freelist).free(0x7048c16870, 0x2, 0x70c2023000)
        /go/pkg/mod/github.com/coreos/bbolt@v1.3.1-coreos.6/freelist.go:143 +0x3d6
github.com/coreos/bbolt.(*node).spill(0x7048171340, 0x10, 0x10)
        /go/pkg/mod/github.com/coreos/bbolt@v1.3.1-coreos.6/node.go:363 +0x208
github.com/coreos/bbolt.(*Bucket).spill(0x70480fc1d8, 0x371f0a069, 0x2fdd220)
        /go/pkg/mod/github.com/coreos/bbolt@v1.3.1-coreos.6/bucket.go:568 +0x476
github.com/coreos/bbolt.(*Tx).Commit(0x70480fc1c0, 0x0, 0x0)
        /go/pkg/mod/github.com/coreos/bbolt@v1.3.1-coreos.6/tx.go:160 +0xed
github.com/coreos/bbolt.(*DB).Update(0x704800a1e0, 0x704821e2c8, 0x0, 0x0)
        /go/pkg/mod/github.com/coreos/bbolt@v1.3.1-coreos.6/db.go:674 +0xe8
github.com/influxdata/influxdb/bolt.(*KVStore).Update(0x7048841780, 0x1c90ea0, 0x7048c17590, 0x70488417a0, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/bolt/kv.go:121 +0xd5
github.com/influxdata/influxdb/kv.(*Service).Initialize(0x704806b0e0, 0x1c90de0, 0x7048869e00, 0x1, 0x704806b140)
        /go/src/github.com/influxdata/influxdb/kv/service.go:60 +0x8d
github.com/influxdata/influxdb/cmd/influxd/launcher.(*Launcher).run(0x7048342480, 0x1c90de0, 0x7048869e00, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/launcher.go:424 +0x115a
github.com/influxdata/influxdb/cmd/influxd/launcher.NewCommand.func1(0x70480a1680, 0x2ffac30, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/launcher.go:77 +0x134
github.com/spf13/cobra.(*Command).execute(0x70480a1680, 0x704803a290, 0x0, 0x0, 0x70480a1680, 0x704803a290)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x70480a1680, 0x0, 0x0, 0x70480a1680)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
        /go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:57 +0x75
exit status 5
```

**Comment by francescolavra** [comment]
influxb 2.0 uses bbolt (https://github.com/etcd-io/bbolt) as database engine, which in turn uses LMDB as low-level library. LMDB uses file-backed mapped memory regions (I could confirm this by looking at the Nanos log), which are currently not supported.

**Comment by eyberg** [comment]
took a quick look at this again ->

```
 ops run -c config.json influxd
[influxd]
booting /home/eyberg/.ops/images/influxd.img ...
assigned: 10.0.2.15
ts=2020-09-10T16:45:21.023229Z lvl=info msg="Welcome to InfluxDB" log_id=0PAEM_~G000 version=2.0.0-alpha.13 commit=d30fd1084 build_date=2019-06-14T00:32:50Z
ts=2020-09-10T16:45:21.056397Z lvl=info msg="Resources opened" log_id=0PAEM_~G000 service=bolt path=/root/.influxdbv2/influxd.bolt
ts=2020-09-10T16:45:21.220436Z lvl=info msg="Index opened" log_id=0PAEM_~G000 service=storage-engine index=tsi partitions=8
ts=2020-09-10T16:45:21.228327Z lvl=info msg="Reloaded WAL" log_id=0PAEM_~G000 service=storage-engine path=/root/.influxdbv2/engine/wal duration=0.683ms
ts=2020-09-10T16:45:21.230673Z lvl=info msg=Starting log_id=0PAEM_~G000 service=storage-engine component=retention_enforcer check_interval=1h
ts=2020-09-10T16:45:21.235644Z lvl=info msg="Starting query controller" log_id=0PAEM_~G000 service=storage-reads concurrency_quota=10 memory_bytes_quota_per_query=9223372036854775807 queue_size=10
ts=2020-09-10T16:45:31.322397Z lvl=error msg="failed to start nats streaming server" log_id=0PAEM_~G000 error="unable to start a NATS Server on localhost:4222"
unable to start a NATS Server on localhost:4222
```

interesting comment ->
https://github.com/influxdata/influxdb/blob/6f0cf049caa1a7982669ee685e86621452686551/cmd/influxd/launcher/launcher.go#L990

**Comment by eyberg** [comment]
this seems to work after plugging in the any interface to resolve to localhost - I couldn't figure out how to do this from the cli though

```
ops run -c config.json -p 4222 -p 8086 -p 9999 influxd
[influxd]
booting /home/eyberg/.ops/images/influxd.img ...
assigned: 10.0.2.15
ts=2020-09-10T17:15:30.191507Z lvl=info msg="Welcome to InfluxDB" log_id=0PAG503W000 version=2.0.0-alpha.13 commit=d30fd1084 build_date=2019-06-14T00:32:50Z
ts=2020-09-10T17:15:30.228268Z lvl=info msg="Resources opened" log_id=0PAG503W000 service=bolt path=/root/.influxdbv2/influxd.bolt
ts=2020-09-10T17:15:30.400382Z lvl=info msg="Index opened" log_id=0PAG503W000 service=storage-engine index=tsi partitions=8
ts=2020-09-10T17:15:30.407933Z lvl=info msg="Reloaded WAL" log_id=0PAG503W000 service=storage-engine path=/root/.influxdbv2/engine/wal duration=0.660ms
ts=2020-09-10T17:15:30.410281Z lvl=info msg=Starting log_id=0PAG503W000 service=storage-engine component=retention_enforcer check_interval=1h
ts=2020-09-10T17:15:30.415525Z lvl=info msg="Starting query controller" log_id=0PAG503W000 service=storage-reads concurrency_quota=10 memory_bytes_quota_per_query=9223372036854775807 queue_size=10
ts=2020-09-10T17:15:31.467297Z lvl=info msg=Starting log_id=0PAG503W000 service=telemetry interval=8h
ts=2020-09-10T17:15:31.473770Z lvl=info msg=Listening log_id=0PAG503W000 service=http transport=http addr=:9999 port=9999

ts=2020-09-10T17:35:51.502678Z lvl=info msg="Snapshot for path written" log_id=0PAG503W000 service=storage-engine engine=tsm1 op_name=tsm1_cache_snapshot path=/root/.influxdbv2/engine/data duration=58.879ms
^Cqemu-system-x86_64: terminating on signal 2
signal: killed
```

```
./influx write -b bob -o NanoVMs -p s   'myMeasurement,host=myHost testField="testData" 1556896326'
```

**Comment by francescolavra** [comment]
I made a package: https://repo.ops.city/v2/packages/francescolavra/influxdb/2.7.1/x86_64/show
